modLoader="javafml"
loaderVersion="[1.16.5,)"
license="MIT"
issueTrackerURL="https://github.com/yourgithubrepo"

[[mods]]
modId="snowballmod"
version="1.0.0"
displayName="Snowball AI Mod"
description="A mod that integrates Snowball AI with Minecraft for chat and command-based input."
